image: python:3.10

cache:
  paths:
    - .pip_cache/

before_script:
  - python -m pip install --upgrade pip
  - pip install sphinx sphinx-autobuild sphinx_rtd_theme pydata-sphinx-theme sphinx.ext.autodoc sphinx.ext.napoleon sphinx-codeautolink sphinx_design sphinx-favicon  sphinxcontrib-applehelp sphinxcontrib-devhelp sphinxcontrib-mermaid ablog

stages:
  - build
  - deploy

build-docs:
  stage: build
  script:
    - cd docs
    - sphinx-apidoc -o source ../pysewer # Regenerate API docs on each build
    - make html
  artifacts:
    paths:
      - docs/_build/html
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
  only:
    - main
