stages:
#   - install
  - deploy  

# install_dependencies:
#   stage: install
#   image: continuumio/anaconda3
#   script:
#     - pip install --upgrade pip
#     - conda env create -f environment.yml
#     - conda activate pysewer
#     - pip install .
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - mkdir public
    - cd docs
    - mv build/html/ ../public
    # - cp build/latex/pysewer.pdf ../public
  artifacts:
    paths:
      - public
    expire_in: 1 month
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH