stages:
  - install
  - deploy  

install_dependencies:
  stage: install
  image: continuumio/miniconda3
  script:
    - pip install --upgrade pip
    - conda env create -f environment.yml
    - conda activate pysewer
    - pip install .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  image: continuumio/miniconda3
  script:
 
    - conda env create -f environment.yml
    - conda activate pysewer
    - pip install --upgrade pip
    - pip install .
    - pip install sphinx sphinx_rtd_theme
    - mkdir public
    - cd docs
    - sphinx-apidoc -o source/ ../pysewer/
    - ls source/
    - make clean
    - make html
    - ls build/html/
    # - make latexpdf
    - cp -r build/html/* ../public
    # - cp build/latex/pysewer.pdf ../public
  artifacts:
    paths:
      - public
    expire_in: 1 month
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH