image: ubuntu:latest

variables:
  CONDA_PKGS_DIRS: "$CI_PROJECT_DIR/.conda_pkgs_dir"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"

cache:
  paths:
    - .conda_pkgs_dir
    - .pip_cache

stages:
  - setup
  - test
  - build
  - deploy

include:
  - local: 'ci/setup.yml'
  - local: 'ci/test.yml'
  - local: 'ci/build.yml'
  - local: 'ci/deploy.yml'

# possible global configurations or jobs that can be added, see hifis course and gitlab ci documentation. 

# For example, add a lint job:
# lint:
#   stage: test
#   image: python:3.10
#   script:
#     - pip install flake8
#     - flake8 .

# Or a security scan job:
# security_scan:
#   stage: test
#   image: python:3.10
#   script:
#     - pip install bandit
#     - bandit -r .