stages:
  - deploy  

pages:
  stage: deploy
  image: python:3.10
  script:
    - pip install --upgrade pip
    - pip install sphinx sphinx_rtd_theme
    - pip install .
    - mkdir public
    - cd docs
    - sphinx-apidoc -o source/ ../pysewer/
    - ls source/
    - make clean
    - make html
    - ls build/html/
    # - make latexpdf
    - cp -r build/html/* ../public
    # - cp build/latex/pysewer.pdf ../public
  artifacts:
    paths:
      - public
    expire_in: 1 month
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH