name: pysewer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.6
  - scipy ==1.11.1
  - geopandas == 0.9.0
  - rasterio == 1.2.10
  - mypy ==0.981
  - matplotlib ==3.7.1
  - ipykernel == 6.25.0
  - scikit-learn ==1.0.2
  - networkx ==3.1
  - notebook ==6.5.4
  - python-dotenv ==0.21.0
  - pyarrow ==11.0.0
  - charset-normalizer == 3.2.0
  - pathlib ==1.0.1
  - earthpy ==0.9.4
  - pytest ==7.4.0
  - pytest-cov ==4.0.0
  - geos ==3.9.1
  - pdoc3 ==0.9.2
  - sphinx ==5.0.2
  - pandas ==2.1.0
  - pyyaml ==6.0
  - fiona ==1.9.4.post1
  - nbconvert == 7.7.4
  - types-pyyaml ==6.0.12.12
  - scikit-image ==0.21.0

