name: pysewer
channels:
  - defaults
dependencies:
  - python=3.10.6
  - scipy
  - pandas=2.1.0
  - geopandas=0.13.2
  - rasterio
  - mypy
  - matplotlib
  - ipykernel
  - momepy
  - scikit-learn
  - earthpy
  - networkx==2.8.4
  - jupyterhub
  - notebook
  - python-dotenv
  - pyarrow
  - charset-normalizer
  - fiona=1.9.4
  - charset-normalizer=3.2.0

