package:
  name: pysewer
  version: 0.1.9

source:
  git_rev: 
  git_url: https://git.ufz.de/sanne/pysewer

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - networkx
    - scipy
    - numpy
    - geopandas
    - matplotlib
    - Shapely>=1.7
    - pyproj
    - scikit-learn
    - earthpy
    - gdal
    - fiona
    - rasterio
    

test:
  imports:
    - pysewer

about:
  home: https://git.ufz.de/sanne/pysewer
