# default settings

# preprocessing
preprocessing:
  dem_file_path: "example_data/1_DEM/dem_10m1.tif"
  roads_input_data: "example_data/3_Roads/roads_projected.shp"
  buildings_input_data: "example_data/2_Buildings/buildings_projected.shp"
  dx: 10 # sampling resolution, get_profile (DEM Class)
  pump_penalty: 1000 # penalty for pumping
  max_connection_length: 30 # connect buildings within this distance

optimization:
  inhabitants_dwelling: 3
  daily_wastewater_person: 0.2
  peak_factor: 2.3 # peak factor for wastewater
  min_slope: -0.01 # min slope required for gravitational flow
  tmax: 8 # max trench depth allowed
  tmin: 0.25 # min trench depth allowed
  inflow_trench_depth: 0
  min_trench_depth: 0
  diameters: [0.1, 0.15, 0.2, 0.25, 0.3, 0.4] # diameters to be considered
  roughness: 0.013 # roughness coefficient
  pressurized_diameter: 0.2

plotting:
  plot_connection_graph: true
  plot_junction_graph: true
  plot_sink: true
  plot_sewer: true
  sewer_graph: null
  info_table: null
  hillshade: true
  colormap: "jet"

export:
  file_format: "gpkg"
