# default settings

# preprocessing
preprocessing:
  dem_file_path: ../tests/test_data/dem.tif
  roads_input_data: ../tests/test_data/roads_clipped.shp
  buildings_input_data: ../tests/test_data/buildings_clipped.shp
  dx: 10 # sampling resolution, get_profile (DEM Class)
  pump_penalty: 1000 # penalty for pumping
  max_connection_length: 30 # connect buildings within this distance

optimization:
  inhabitants_dwelling: 3
  daily_wastewater_person: 0.2
  peak_factor: 2.3 # peak factor for wastewater
  min_slope: -0.01 # min slope required for gravitational flow
  tmax: 8 # max trench depth allowed
  tmin: 0.25 # min trench depth allowed
  inflow_trench_depth: 0
  min_trench_depth: 0
  diameters: [0.3, 0.4, 0.5] # diameters to be considered
  roughness: 0.013 # roughness coefficient
  pressurized_diameter: 0.2

plotting:
  plot_connection_graph: true
  plot_junction_graph: true
  plot_sink: true
  plot_sewer: true
  sewer_graph: null
  info_table: null
  hillshade: true
  colormap: "jet"

export:
  file_format: "gpkg"
