name: Test

on: [push, pull_request, workflow_call]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge gdal fiona shapely pytest
          pip install .

      - name: Run tests
        shell: bash -l {0}
        run: pytest
