name: Draft PDF
on:
  push:
    paths:
      - paper/**
      - .github/workflows/draft-pdf.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List files for debugging
        run: ls -R

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # Update this path based on the actual location of paper.md
          paper-path: paper/paper.md

      - name: Move PDF to paper directory
        run: mv paper.pdf paper/paper.pdf

      - name: Commit and push PDF
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add paper/paper.pdf
          git commit -m 'Add compiled PDF'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf